# 注册中心地址
registry:
  enabled: false
  type: nacos # 注册中心类型 暂时只支持 nacos
  server: 127.0.0.1
  port: 8848
  # 负载均衡策略  需继承org.noexcs.loadBalance.AbstractLoadBalance
  loadBalancer: org.noexcs.loadBalance.impl.RandomBalance
  # 服务名称
  serviceName: rpc-public

# 当注册中心不存在时，会使用下面的地址
provider:
  server: 127.0.0.1
  port: 8007

timed-out: 3 # 超时时间设置（单位秒）, -1不超时，默认-1
retries: 3 # 失败重试次数，默认1
serializer: org.noexcs.codec.Impl.HessianSerializer # 序列化方式类名，HessianSerializer为默认，需实现org.noexcs.codec.Serializer接口